import time

import numpy as np


def exercise_045():
    """
    Triangle, pentagonal, and hexagonal numbers are generated by the following
    formulae:

    Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.

    :return: Next triangle number that is also pentagonal and hexagonal.
    :rtype: int
    """

    n = 143
    x = 40755
    while True:
        x += 4 * n + 1
        i = (-1 + np.sqrt(1 + 8 * x)) / 2
        j = (1 + np.sqrt(1 + 24 * x)) / 6
        k = (1 + np.sqrt(1 + 8 * x)) / 4
        if i % 1 == 0 and j % 1 == 0 and k % 1 == 0:
            return x
        n += 1


if __name__ == '__main__':
    start_time = time.time()
    print(exercise_045())
    end_time = time.time()
    print('{} s'.format(end_time - start_time))
